"""agent config

Revision ID: 7e3470070211
Revises: 7e5933c5ff72
Create Date: 2026-07-01 01:12:28.556379

"""
from alembic import op
import sqlalchemy as sa


revision = '7e3470070211'
down_revision = '7e5933c5ff72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'config')
    # ### end Alembic commands ###
