"""agent type

Revision ID: 7e5933c5ff72
Revises: 9ca42e6f50ec
Create Date: 2026-07-01 00:47:53.562214

"""
from alembic import op
import sqlalchemy as sa


revision = '7e5933c5ff72'
down_revision = '9ca42e6f50ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('type', sa.String(), server_default='custom', nullable=False))
    op.create_index(op.f('ix_agents_type'), 'agents', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_type'), table_name='agents')
    op.drop_column('agents', 'type')
    # ### end Alembic commands ###
