"""agents table

Revision ID: 9ca42e6f50ec
Revises: cb4561777c61
Create Date: 2026-07-01 00:14:23.495636

"""
from alembic import op
import sqlalchemy as sa


revision = '9ca42e6f50ec'
down_revision = 'cb4561777c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('greeting', sa.Text(), nullable=True),
    sa.Column('voice', sa.String(), server_default='alloy', nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_slug'), 'agents', ['slug'], unique=True)
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_slug'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
